language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - "mkdir -p ~/.composer"
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - phpunit -c app/ -d error_reporting=0 --coverage-text --coverage-clover=coverage.clover
  - ./bin/phpcs --standard=PSR2 src/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
