language: php

php:
  - 7.1
  - 7.0
  - 5.6

before_script:
  - "mkdir -p ~/.composer"
  - composer install --prefer-source --no-interaction

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - ./vendor/bin/phpcs --standard=PSR2 src/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
