language: php

php:
  - 7.1
  - 7.0
  - 5.6

before_script:
  - "mkdir -p ~/.composer"
  - composer install --prefer-source --no-interaction

script:
  - composer test
  - composer lint

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
