language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - "mkdir -p ~/.composer"
  - composer self-update
  - composer install --prefer-source --optimize-autoloader

script: phpunit -c app/ -d error_reporting=0
