imports:
    - { resource: default_parameters.yml }
    - { resource: parameters.yml }

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: ['php']
    default_locale:  "%locale%"

app:
    master:
        storage: "%app.master.storage%"
        path:    "%app.master.path%"
        filters: "%app.master.filters%"
    slave:
        storage: "%app.slave.storage%"
        path:    "%app.slave.path%"
        path_tpl: "%app.slave.path_tpl%"
        filters: "%app.slave.filters%"
