imports:
    - { resource: config_dev.yml }

framework:
    test: ~

app:
    master:
        storage: local
        path:    "vfs://root/source"
        filters:
            path: { pattern: "~[A-Z]{4}/stream/.*\\.mov~" }
            excludeEpisodes: { path: "vfs://root/exclude-episodes.json" }
            excludeShows: { path: "vfs://root/exclude-shows.json" }
    slave:
        storage: local
        path:    "vfs://root/dest"
        path_tpl: "/__program__/__uid__"
        filters:
