parameters:
    app.logger: file
    app.name: app

    file.log.path: %kernel.logs_dir%/sync.log

    elastic.log.index: sync
    elastic.log.type: app
    elastic.client.config:
        host: localhost