services:
    # Logs
    app_logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: ["app"]
        calls:
            - [pushHandler, [@log_handler]]
    log_handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/sync.log, 200]
        calls:
            - [setFormatter, [@log_formatter]]
    log_formatter:
    #    class: Monolog\Formatter\LogstashFormatter
    #    arguments: ["dir-sync"]
        class: Monolog\Formatter\LineFormatter

    # Storage services
    storage.local:
        class: AppBundle\Sync\Storage\Local
        public: false
    storage.lto:
        class: AppBundle\Sync\Storage\Lto
        public: false

    # Filters
    filter.path:
        class: AppBundle\Sync\Entity\Filter\Path
        scope: prototype

    app:
        class: AppBundle\Sync\Sync
        calls:
            - [setMasterStorage, [@master.storage]]
            - [setMasterPath, [%master.path%]]
            - [setSlaveStorage, [@slave.storage]]
            - [setSlavePath, [%slave.path%]]
            - [setSlavePathTpl, ["%slave.path%%slave.path_tpl%"]]
            - [setLogger, [@app_logger]]