services:
    # Logs
    app.logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: ["%app.name%"]
        calls:
            - [pushHandler, ["@log.handler"]]

    # Process locker
    app.locker:
        class: Hope\Locker\FileLocker
        arguments: ["%app.name%", "%kernel.root_dir%/../var/lock"]

    # File logger (default: var/logs/sync.log)
    file.log.handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%file.log.path%, 200]
        calls:
            - [setFormatter, ["@file.log.formatter"]]
        lazy: true
    file.log.formatter:
        class: Monolog\Formatter\LineFormatter
        lazy: true

    # Storage services
    storage.local:
        class: AppBundle\Sync\Storage\Local
        public: false
    storage.lto:
        class: AppBundle\Sync\Storage\Lto
        public: false

    # Filters
    filter.path:
        class: AppBundle\Sync\Entity\Filter\Path
        scope: prototype
    filter.excludeEpisodes:
        class: AppBundle\Sync\Entity\Filter\ExcludeEpisodes
        scope: prototype
    filter.excludeShows:
        class: AppBundle\Sync\Entity\Filter\ExcludeShows
        scope: prototype

    # Main App
    app:
        class: AppBundle\Sync\Sync
        calls:
            - [setMasterStorage, ["@master.storage"]]
            - [setMasterPath, ["%master.path%"]]
            - [setSlaveStorage, ["@slave.storage"]]
            - [setSlavePath, ["%slave.path%"]]
            - [setSlavePathTpl, ["%slave.path%%slave.path_tpl%"]]
            - [setLogger, ["@app.logger"]]
            - [setLocker, ["@app.locker"]]
