parameters:
    app.logger: file
    app.name: app

    file.log.path: %kernel.logs_dir%/sync.log

    elastic.log.index: sync
    elastic.log.type: app
    elastic.client.config:
        host: localhost

services:
    # Logs
    app.logger:
        class: Symfony\Bridge\Monolog\Logger
        arguments: [%app.name%]
        calls:
            - [pushHandler, [@log.handler]]
    # File logger (default: app/logs/sync.log)
    file.log.handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%file.log.path%, 200]
        calls:
            - [setFormatter, [@file.log.formatter]]
        lazy: true
    file.log.formatter:
        class: Monolog\Formatter\LineFormatter
        lazy: true

    # Elastic logger
    elastic.log.handler:
        class: Monolog\Handler\ElasticSearchHandler
        arguments: [@elastic.client, { index: %elastic.log.index%, type: %elastic.log.type% }]
        lazy: true
    elastic.client:
        class: Elastica\Client
        arguments: [%elastic.client.config%]
        lazy: true

    # Storage services
    storage.local:
        class: AppBundle\Sync\Storage\Local
        public: false
    storage.lto:
        class: AppBundle\Sync\Storage\Lto
        public: false

    # Filters
    filter.path:
        class: AppBundle\Sync\Entity\Filter\Path
        scope: prototype
    filter.exclude:
        class: AppBundle\Sync\Entity\Filter\Exclude
        scope: prototype

    # Main App
    app:
        class: AppBundle\Sync\Sync
        calls:
            - [setMasterStorage, [@master.storage]]
            - [setMasterPath, [%master.path%]]
            - [setSlaveStorage, [@slave.storage]]
            - [setSlavePath, [%slave.path%]]
            - [setSlavePathTpl, ["%slave.path%%slave.path_tpl%"]]
            - [setLogger, [@app.logger]]